import type { Template } from '../types'

export const TEMPLATES: Template[] = [
  {
    id: 'saas-app',
    name: 'SaaS アプリケーション',
    description: 'マルチテナント対応、認証・決済統合、管理ダッシュボード完備',
    icon: '🚀',
    popular: true,
    techStack: [
      'Next.js 16',
      'TypeScript',
      'Tailwind CSS',
      'shadcn/ui',
      'Prisma',
      'PostgreSQL',
      'NextAuth.js',
      'Stripe',
    ],
  },
  {
    id: 'admin-dashboard',
    name: 'Admin Dashboard',
    description: 'データ可視化、分析機能、CRUD操作に最適化',
    icon: '📊',
    popular: true,
    techStack: [
      'Next.js 16',
      'React 19',
      'TypeScript',
      'Tailwind CSS v4',
      'shadcn/ui',
      'Recharts',
      'Tanstack Table',
    ],
  },
  {
    id: 'ecommerce',
    name: 'Eコマース',
    description: '商品管理、カート、決済、注文管理システム',
    icon: '🛒',
    popular: true,
    techStack: [
      'Next.js 16',
      'TypeScript',
      'Tailwind CSS',
      'Drizzle ORM',
      'PostgreSQL',
      'Stripe',
      'Cloudinary',
    ],
  },
  {
    id: 'blog-cms',
    name: 'ブログ / CMS',
    description: 'コンテンツ管理、SEO最適化、MDX対応',
    icon: '✍️',
    techStack: [
      'Next.js 16',
      'TypeScript',
      'Tailwind CSS',
      'MDX',
      'Contentlayer',
      'Vercel Analytics',
    ],
  },
  {
    id: 'landing-page',
    name: 'ランディングページ',
    description: 'マーケティング特化、高速表示、コンバージョン最適化',
    icon: '🎯',
    techStack: [
      'Next.js 16',
      'TypeScript',
      'Tailwind CSS',
      'Framer Motion',
      'React Hook Form',
      'Zod',
    ],
  },
  {
    id: 'api-backend',
    name: 'API バックエンド',
    description: 'RESTful API、認証、レート制限、ドキュメント自動生成',
    icon: '⚙️',
    techStack: [
      'Next.js 16 API Routes',
      'TypeScript',
      'Prisma',
      'PostgreSQL',
      'Zod',
      'NextAuth.js',
      'Swagger',
    ],
  },
]
